# returns the list of phonetic features of an IPA symbol **CAN ONLY HANDLE ROMAN LETTERS** (TODO obscure IPA symbols)
def featureDispenser(inputChar):
                    #bilabial
    featureDict = {"p": ["+consonantal", "-sonorant", "-continuant", 
                         "-delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "-voice", "-spread glottis",
                         "-constricted glottis", "+labial", "-round", "-labiodental",
                         "-coronal", "0anterior", "0distributed", "0strident", "-lateral",
                         "-dorsal", "0ALLVOWEL"], 
                   "b" : ["+consonantal", "-sonorant", "-continuant", 
                         "-delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "+voice", "-spread glottis",
                         "-constricted glottis", "+labial", "-round", "-labiodental",
                         "-coronal", "0anterior", "0distributed", "0strident", "-lateral",
                         "-dorsal", "0ALLVOWEL"],
                   "m" : ["+consonantal", "+sonorant", "-continuant", 
                         "0delayed release", "-approximant", "-tap", 
                         "-trill", "+nasal", "+voice", "-spread glottis",
                         "-constricted glottis", "+labial", "-round", "-labiodental",
                         "-coronal", "0anterior", "0distributed", "0strident", "-lateral",
                         "-dorsal", "0ALLVOWEL"],
                   #labiodental
                   "f" : ["+consonantal", "-sonorant", "+continuant", 
                         "+delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "-voice", "-spread glottis",
                         "-constricted glottis", "+labial", "-round", "+labiodental",
                         "-coronal", "0anterior", "0distributed", "0strident", "-lateral",
                         "-dorsal", "0ALLVOWEL"],
                   "v" : ["+consonantal", "-sonorant", "+continuant", 
                         "+delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "+voice", "-spread glottis",
                         "-constricted glottis", "+labial", "-round", "+labiodental",
                         "-coronal", "0anterior", "0distributed", "0strident", "-lateral",
                         "-dorsal", "0ALLVOWEL"],
                   #alveolar
                   "t" : ["+consonantal", "-sonorant", "-continuant", 
                         "-delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "-voice", "-spread glottis",
                         "-constricted glottis", "-labial", "-round", "-labiodental",
                         "+coronal", "+anterior", "-distributed", "-strident", "-lateral",
                         "-dorsal", "0ALLVOWEL"],
                   "d" : ["+consonantal", "-sonorant", "-continuant", 
                         "-delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "+voice", "-spread glottis",
                         "-constricted glottis", "-labial", "-round", "-labiodental",
                         "+coronal", "+anterior", "-distributed", "-strident", "-lateral",
                         "-dorsal", "0ALLVOWEL"],
                  "s" : ["+consonantal", "-sonorant", "+continuant", 
                         "+delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "-voice", "-spread glottis",
                         "-constricted glottis", "-labial", "-round", "-labiodental",
                         "+coronal", "+anterior", "-distributed", "+strident", "-lateral",
                         "-dorsal", "0ALLVOWEL"],
                   #TO REPRESENT ESH SYMBOL IPA
                   "esh" : ["+consonantal", "-sonorant", "+continuant", 
                         "+delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "-voice", "-spread glottis",
                         "-constricted glottis", "-labial", "-round", "-labiodental",
                         "+coronal", "-anterior", "+distributed", "+strident", "-lateral",
                         "-dorsal", "0ALLVOWEL"],
                  "z" : ["+consonantal", "-sonorant", "+continuant", 
                         "+delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "+voice", "-spread glottis",
                         "-constricted glottis", "-labial", "-round", "-labiodental",
                         "+coronal", "+anterior", "-distributed", "+strident", "-lateral",
                         "-dorsal", "0ALLVOWEL"],
                  "n" : ["+consonantal", "+sonorant", "-continuant", 
                         "0delayed release", "-approximant", "-tap", 
                         "-trill", "+nasal", "+voice", "-spread glottis",
                         "-constricted glottis", "-labial", "-round", "-labiodental",
                         "+coronal", "+anterior", "-distributed", "-strident", "-lateral",
                         "-dorsal", "0ALLVOWEL"],
                  "l" : ["+consonantal", "+sonorant", "+continuant", 
                         "0delayed release", "+approximant", "-tap", 
                         "-trill", "-nasal", "+voice", "-spread glottis",
                         "-constricted glottis", "+labial", "-round", "-labiodental",
                         "+coronal", "+anterior", "-distributed", "-strident", "+lateral",
                         "-dorsal", "0ALLVOWEL"], 
                   #velar
                   "k" : ["+consonantal", "-sonorant", "-continuant", 
                         "-delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "-voice", "-spread glottis",
                         "-constricted glottis", "-labial", "-round", "-labiodental",
                         "-coronal", "0anterior", "0distributed", "0strident", "-lateral",
                         "+dorsal", "+high", "-low", "0ALLVOWEL"],
                   "g" : ["+consonantal", "-sonorant", "-continuant", 
                         "-delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "+voice", "-spread glottis",
                         "-constricted glottis", "-labial", "-round", "-labiodental",
                         "-coronal", "0anterior", "0distributed", "0strident", "-lateral",
                         "+dorsal", "+high", "-low", "0ALLVOWEL"],
                   #glottal
                   "h" : ["-consonantal", "-sonorant", "+continuant", 
                         "+delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "-voice", "+spread glottis",
                         "-constricted glottis", "-labial", "-round", "-labiodental",
                         "-coronal", "0anterior", "0distributed", "0strident", "-lateral",
                         "-dorsal", "0ALLVOWEL"],
                   
                   
                  #vowels
                  "a" : ["0ALLCONSONANT", "-high", "+low", "0tense", "-front", "-back", "-round"],
                  "e" : ["0ALLCONSONANT", "-high", "-low", "+tense", "+front", "-back", "-round"],
                  "i" : ["0ALLCONSONANT", "+high", "-low", "+tense", "+front", "-back", "-round"],
                  "o" : ["0ALLCONSONANT", "-high", "-low", "+tense", "-front", "+back", "+round"],
                  "u" : ["0ALLCONSONANT", "+high", "-low", "+tense", "-front", "+back", "+round"],}
                    
    
    allFeatures = ["syllabic","stress", "long", "consonantal", "sonorant", "continuant", 
                   "delayed release","approximant", "tap","trill","nasal","voice","spread glottis",
                   "constricted glottis","labial","round", "labiodental", "coronal",
                   "anterior", "distributed", "strident", "lateral", "dorsal",
                    
                   #for vowels (and glides)
                    "high","low","front","back","tense"]
    
    
    return(featureDict[inputChar])

print(featureDispenser("h"))
