# returns the list of phonetic features of an IPA symbol **CAN ONLY HANDLE ROMAN LETTERS** (TODO IPA symbol)
def featureDispenser(inputChar):
                    #bilabial
    featureDict = {"p": ["+consonantal", "-sonorant", "-continuant", 
                         "-delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "-voice", "-spread glottis",
                         "-constricted glottis", "+labial", "-round", "-labiodental",
                         "-coronal", "0anterior", "0distributed", "0strident", "-lateral",
                         "dorsal", "0ALLVOWEL"], 
                   "b" : ["+consonantal", "-sonorant", "-continuant", 
                         "-delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "+voice", "-spread glottis",
                         "-constricted glottis", "+labial", "-round", "-labiodental",
                         "-coronal", "0anterior", "0distributed", "0strident", "-lateral",
                         "dorsal", "0ALLVOWEL"],
                   "m" : ["+consonantal", "+sonorant", "-continuant", 
                         "0delayed release", "-approximant", "-tap", 
                         "-trill", "+nasal", "+voice", "-spread glottis",
                         "-constricted glottis", "+labial", "-round", "-labiodental",
                         "-coronal", "0anterior", "0distributed", "0strident", "-lateral",
                         "dorsal", "0ALLVOWEL"],
                   #labiodental
                   "f" : ["+consonantal", "-sonorant", "+continuant", 
                         "+delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "-voice", "-spread glottis",
                         "-constricted glottis", "+labial", "-round", "+labiodental",
                         "-coronal", "0anterior", "0distributed", "0strident", "-lateral",
                         "dorsal", "0ALLVOWEL"],
                   "v" : ["+consonantal", "-sonorant", "+continuant", 
                         "+delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "+voice", "-spread glottis",
                         "-constricted glottis", "+labial", "-round", "+labiodental",
                         "-coronal", "0anterior", "0distributed", "0strident", "-lateral",
                         "dorsal", "0ALLVOWEL"],
                   #alveolar
                   "t" : ["+consonantal", "-sonorant", "-continuant", 
                         "-delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "-voice", "-spread glottis",
                         "-constricted glottis", "-labial", "-round", "-labiodental",
                         "+coronal", "+anterior", "-distributed", "-strident", "-lateral",
                         "dorsal", "0ALLVOWEL"],
                   "d" : ["+consonantal", "-sonorant", "-continuant", 
                         "-delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "+voice", "-spread glottis",
                         "-constricted glottis", "-labial", "-round", "-labiodental",
                         "+coronal", "+anterior", "-distributed", "-strident", "-lateral",
                         "dorsal", "0ALLVOWEL"],
                  "s" : ["+consonantal", "-sonorant", "+continuant", 
                         "+delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "-voice", "-spread glottis",
                         "-constricted glottis", "-labial", "-round", "-labiodental",
                         "+coronal", "+anterior", "-distributed", "+strident", "-lateral",
                         "dorsal", "0ALLVOWEL"],
                  "z" : ["+consonantal", "-sonorant", "+continuant", 
                         "+delayed release", "-approximant", "-tap", 
                         "-trill", "-nasal", "+voice", "-spread glottis",
                         "-constricted glottis", "-labial", "-round", "-labiodental",
                         "+coronal", "+anterior", "-distributed", "+strident", "-lateral",
                         "dorsal", "0ALLVOWEL"],
                  "n" : ["+consonantal", "+sonorant", "-continuant", 
                         "0delayed release", "-approximant", "-tap", 
                         "-trill", "+nasal", "+voice", "-spread glottis",
                         "-constricted glottis", "-labial", "-round", "-labiodental",
                         "+coronal", "+anterior", "-distributed", "-strident", "-lateral",
                         "dorsal", "0ALLVOWEL"],
                  "l" : ["+consonantal", "+sonorant", "+continuant", 
                         "0delayed release", "+approximant", "-tap", 
                         "-trill", "-nasal", "+voice", "-spread glottis",
                         "-constricted glottis", "+labial", "-round", "-labiodental",
                         "+coronal", "+anterior", "-distributed", "-strident", "+lateral",
                         "dorsal", "0ALLVOWEL"]}
                    
    
    allFeatures = ["syllabic",
    "stress",
    "long",
    "consonantal",
    "sonorant",
    "continuant",
    "delayed release",
    "approximant",
    "tap",
    "trill",
    "nasal",
    "voice",
    "spread glottis",
    "constricted glottis",
    "labial",
    "round",
    "labiodental",
    "coronal",
    "anterior",
    "distributed",
    "strident",
    "lateral",
    "DORSAL",
    #for vowels (and glides)
    "high",
    "low",
    "front",
    "back",
    "tense"]
    
    
    print(featureDict[inputChar])

featureDispenser("m")
